import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    padding: 60,
    backgroundColor: '#FFFFFF',
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 30,
  },
  senderInfo: {
    fontSize: 10,
    color: '#374151',
    lineHeight: 1.5,
    marginBottom: 20,
  },
  date: {
    fontSize: 10,
    color: '#6B7280',
    marginBottom: 20,
  },
  recipientInfo: {
    fontSize: 10,
    color: '#374151',
    lineHeight: 1.5,
    marginBottom: 20,
  },
  greeting: {
    fontSize: 11,
    color: '#1F2937',
    marginBottom: 15,
    fontWeight: 'bold',
  },
  paragraph: {
    fontSize: 10,
    color: '#374151',
    lineHeight: 1.6,
    marginBottom: 12,
    textAlign: 'justify',
  },
  closing: {
    fontSize: 10,
    color: '#1F2937',
    marginTop: 15,
    marginBottom: 5,
  },
  signature: {
    fontSize: 11,
    color: '#1F2937',
    fontWeight: 'bold',
    marginTop: 30,
  },
  footer: {
    position: 'absolute',
    bottom: 40,
    left: 60,
    right: 60,
    fontSize: 8,
    color: '#9CA3AF',
    textAlign: 'center',
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    paddingTop: 10,
  },
  accent: {
    color: '#6366F1',
    fontWeight: 'bold',
  },
});

interface CoverLetterData {
  senderName: string;
  senderEmail: string;
  senderPhone: string;
  senderAddress: string;
  date: string;
  recipientName: string;
  recipientTitle: string;
  companyName: string;
  companyAddress: string;
  jobTitle: string;
  paragraphs: string[];
}

interface CoverLetterProps {
  data: CoverLetterData;
}

export const CoverLetter: React.FC<CoverLetterProps> = ({ data }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      {/* Sender Information */}
      <View style={styles.header}>
        <Text style={styles.senderInfo}>
          {data.senderName}{'\n'}
          {data.senderEmail}{'\n'}
          {data.senderPhone}{'\n'}
          {data.senderAddress}
        </Text>

        {/* Date */}
        <Text style={styles.date}>{data.date}</Text>

        {/* Recipient Information */}
        <Text style={styles.recipientInfo}>
          {data.recipientName}{'\n'}
          {data.recipientTitle}{'\n'}
          {data.companyName}{'\n'}
          {data.companyAddress}
        </Text>
      </View>

      {/* Greeting */}
      <Text style={styles.greeting}>
        Dear {data.recipientName || 'Hiring Manager'},
      </Text>

      {/* Letter Body */}
      {data.paragraphs.map((paragraph, index) => (
        <Text key={index} style={styles.paragraph}>
          {paragraph}
        </Text>
      ))}

      {/* Closing */}
      <View style={{ marginTop: 20 }}>
        <Text style={styles.closing}>Sincerely,</Text>
        <Text style={styles.signature}>{data.senderName}</Text>
      </View>

      {/* Footer */}
      <View style={styles.footer}>
        <Text>Generated by CV Tailor Agent • Tailored for {data.companyName}</Text>
      </View>
    </Page>
  </Document>
);

export default CoverLetter;
